GET http://localhost:5000/localhost:5000/users

###
GET http://localhost:5000/suppliers/1

###
POST http://localhost:5000/suppliers
Content-Type: : application/json
{
    "nama": "Indomilk",
    "email": "indomilk@gmail.com",
    "alamat": "Cikarang"
}
###
DELETE  http://localhost:5000/suppliers/123200054
